---
title: "Arthrobacyter inoculation in mono-association system"
subtitle: "Shimasai et al. Nicotine SynComs"
author: "Tomohisa Shimasaki"
format:
  html: default
  pdf: default
---

# Setup
```{r setup}
# Global setup
rm(list = ls())
options(warn = -1)

library(stringr, quietly = T, warn.conflicts = F)
library(ggplot2, quietly = T, warn.conflicts = F)
library(reshape2, quietly = T, warn.conflicts = F)
library(dplyr, quietly = T, warn.conflicts = F)
library(tidyverse, quietly = T, warn.conflicts = F)
library(readxl, quietly = T, warn.conflicts = F)
library(here, quietly = T, warn.conflicts = F)
library(effectsize)
```

# Path
```{r path}
data_dir <- here("05_Arthrobacter_inoculation", "input")
fig_dir <- here("05_Arthrobacter_inoculation", "output")
```

# Load Data
```{r load-data}
tab <- read_excel(file.path(data_dir, "CFU_mono-association-system.xlsx"))
```

# CFU calculation
```{r}
tab$CFU <- (tab$count / tab$`plated volume (ml)`) * 10^3
tab$CFU_g <- tab$CFU / tab$`root weight (mg)` / 10^5

# removing samples with root weight below 15 g
tab <- tab[tab$`root weight (mg)` > 15, ]
```

# ggplot factor setup and label formatting
```{r}
tab$Bacteria <- factor(tab$Bacteria, levels = c("wild-type", "ΔndhL", "VC"))
tab$Plant <- factor(tab$Plant, levels = c("wild-type", "ERF189/199"))
tab$treatment <- factor(tab$treatment, levels = c("WT_WT", "ndhL_WT", "VC_WT", "WT_ERF", "ndhL_ERF", "VC_ERF"))
colors <- data.frame(
  SynCom = c("WT_WT", "ndhL_WT", "VC_WT", "WT_ERF", "ndhL_ERF", "VC_ERF"),
  color = c("#008B8B", "#6B8E23", "#EE6363", "#6CA6CD", "#8FBC8F", "#EEA9B8")
)
```

# Plot data
```{r}
p1 <- ggplot(tab, aes(x = Bacteria, y = CFU_g, fill = treatment)) +
  geom_boxplot(outlier.colour = NA) +
  geom_jitter(aes(shape = batch), size = 1.2, width = 0.1, alpha = 0.8) +
  scale_fill_manual(values = colors$color) +
  facet_grid(. ~ Plant) +
  theme_classic(base_size = 20) +
  theme(
    axis.ticks = element_line(colour = "black"),
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 15, color = "black"),
    axis.title.y = element_text(size = 12),
    axis.title.x = element_blank(),
    legend.position = "right",
    legend.text = element_text(size = 8, color = "black"),
    legend.title = element_text(size = 8, color = "black"),
    strip.text.x = element_blank()
  ) +
  ylab("")
p1
```

# Save plot
```{r}
ggsave(p1, file = paste(fig_dir, "Single_inoculation_CFU.pdf", sep = "/"), width = 6, height = 4, bg = "transparent")
```

# two-way ANOVA with Tukey’s honest significant difference (HSD) test 
```{r}
model <- aov(CFU_g ~ Bacteria * Plant, data = tab)
Turkey <- TukeyHSD(model)

print(summary(model))
eta_squared(model)
print(Turkey)
```
