---
title: "Absolute quantification of Arthrobacter by dPCR"
subtitle: "Shimasai et al. Nicotine SynComs"
author: "Tomohisa Shimasaki"
format:
  html: default
  pdf: default
---

# Setup
```{r setup}
# Global setup
rm(list = ls())
options(warn = -1)

library(ggplot2, quietly = T, warn.conflicts = F)
library(dplyr, quietly = T, warn.conflicts = F)
library(tidyverse, quietly = T, warn.conflicts = F)
library(readxl, quietly = T, warn.conflicts = F)
library(here, quietly = T, warn.conflicts = F)
library(effectsize, quietly = T, warn.conflicts = F)
```

# Path
```{r path}
data_dir <- here("08_SynCom_Arthrobacter_dPCR", "input")
fig_dir <- here("08_SynCom_Arthrobacter_dPCR", "output")
```

# Load Data
```{r load-data}
tab <- read_excel(file.path(data_dir, "SynCom_Arthrobacter_dPCR.xlsx"))
```

# ggplot factor setup and label formatting
```{r}
tab$cp_mg    <-  tab$Copy/tab$`Weight (mg)`

tab$treatment  <-  factor(tab$treatment, levels=c("WT_A02","WT_ndhL", "WT_Con",
                                                    "ERF_A02", "ERF_ndhL", "ERF_Con"))

colors <- data.frame(SynCom=c("WT_WT", "WT_ndhL", "WT_Con", "ERF_WT", "ERF_ndhL", "ERF_Con"),
                     color=c("#008B8B", "#6B8E23", "#EE6363", "#6CA6CD", "#8FBC8F", "#EEA9B8"))
tab$`Sample name`      <- factor(tab$`Sample name`, levels=colors$SynCom)

tab$SynCom     <- factor(tab$SynCom, levels=c("wildSC", "ndhLSC", "conSC")) 
tab$Plant      <- factor(tab$Plant, levels=c("Wild-type", "erf189"))
```

## ggplot factor setup and label formatting
```{r}
p1  <-   ggplot(tab, aes(x= SynCom, y=cp_mg)) +
  geom_boxplot(aes(fill=treatment), outlier.shape = NA) +
  geom_jitter(alpha=0.8, width=0.1, size=1.2) +
         #stat_summary(fun = mean, geom = "crossbar", size = 0.4, width = 0.3, position=position_dodge(0.9)) +
        scale_fill_manual(values = colors$color) +
  theme_classic(base_size = 15) +
  scale_y_continuous(limits = c(0, 120000)) +
                     #labels = scales::label_scientific(notation = "E")) +
  facet_grid(.~Plant) +
  labs(y="Abusolute abundance \n (copies/mg root)", x="") +
  theme(axis.ticks=element_line(colour = "black"), 
        axis.text.x =element_blank(),
        axis.text.y =element_text(size= 10, colour = "black"),
        axis.title.x = element_text(size= 12, colour = "black"),
        axis.title.y = element_text(size= 12, colour = "black"),
        legend.position = "right",
        legend.text = element_text(size= 8, colour = "black"),
        strip.text.x = element_blank())
p1
```

## Save plot
```{r}
ggsave(p1, file = paste(fig_dir, "SynCom_Arthrobacter_dPCR.pdf", sep = "/"), width = 5, height = 4, bg = "transparent")
```

## two-way ANOVA with Tukey’s honest significant difference (HSD) test
```{r}
model  <- aov(cp_mg ~ SynCom*Plant, data=tab)
Turkey <- TukeyHSD(model)

summary(model)
eta_squared(model)
print(Turkey)
```